version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        working_dir: /app    
        volumes:
            - ./app:/app
            - ./app/vendor:/app/vendor
            - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    stripe:
        image: stripe/stripe-cli:latest
        entrypoint: [ "stripe", "listen", "--forward-to", "http://php/payment/handleStripeWebhook" ]
        environment:
            - STRIPE_API_KEY="sk_test_51PT20QFOgvMrJQDgldkFAmxn37UrQBbgHCk67Y2B8VFtNlvZfRvWeBaitTSmAUeghkAHOUzoXgOKtxHhc7nJ7OBJ00UI6zgWwM"
        depends_on:
            - php
        networks:
            - default
# Local DB - Local DB is here in case something happens to DB or for future tests.
#    mysql:
#        image: mariadb:latest
#        environment:
#            MYSQL_ROOT_PASSWORD: secret123
#            MYSQL_USER: user
#            MYSQL_PASSWORD: password
#            MYSQL_DATABASE: haarlemdb
#
#        volumes:
#            - mysqldata:/var/lib/mysql
#            - ./sql:/docker-entrypoint-initdb.d
#        ports:
#            - 3306:3306
    phpmyadmin:
        image: phpmyadmin:latest
        environment:
# Local DB - for switching to Local DB uncomment below, and comment the other environment properties.
#            PMA_HOST: mysql
#            PMA_USER: root
#            PMA_PASSWORD: secret123
# Server DB
            PMA_HOST: 45.32.235.205
            PMA_USER: ignas
            PMA_PASSWORD: 757b3236c44ab612c81cca97
        ports:
            - 8080:80
volumes:
    mysqldata: {}